### ISSUE TITLE
Concurrent Access

### ISSUE THREAD

**Issue by corporatepiyush** [d3x0r/gun-file#4]
What about concurrent access and update operations requested from many Node processes? 
Will it be able to maintain a consistent state?

**Comment by d3x0r** [comment]
There is no locking on the file to synchronize that.  Better to just let them have their own data stores and connect to the central 'authoritative' version.
I think it might? But there's also no catch on the open for file in use... maybe that would be enough, if in-use throw a delayed retry.
The file usage by gun is read once write many.  So, the file has no way to merge what one gun node things from a different once; which goes back to should just let gun handle the conflicts.  Even if another node wrote to the file, the file update itself wouldn't be seen by any other process except those that start after the write.

**Comment by corporatepiyush** [comment]
Ouch ! that would make it almost impossible to scale vertically by default.

Do you think the changes you suggested should be better handled in Gun core library itself than this extension? 

The reason why am I asking this question is, to seek a solution to scale the GunDB instance vertically on multiple CPU cores and also efficiently makes use of available RAM. So i have two options i.e. cluster node module or worker threads in node v11.

**Comment by d3x0r** [comment]
hmm; there are some like gun->mongo adapaters.
I Have a gun->sqlite (ODBC) apter, but I disabled some of the logging because I use them as private databases for each service...
But just connecting the stack in a mesh will let Gun resolve the data...
using the ODBC instead of sqlite would let the connection happen to mysql/postgresql or something, and that would handle shared requests better....
https://github.com/d3x0r/gun-db
