### ISSUE TITLE
gun-file should not attach unless explicitly called.

### ISSUE THREAD

**Issue by alancnet** [d3x0r/gun-file#5]
This is just a minor design critique. Why export `attach`, and then call it automatically? I should be able to instantiate Gun twice, and attach gun-file to a single instance.

**Comment by d3x0r** [comment]
Well... each gun instance has the option of specifying options to enable/disable it per instance(?).
I concur with your assertion... I'm not entirely sure why other than probably individual options can control it.

**Comment by alancnet** [comment]
True true.

**Comment by d3x0r** [comment]
I think attach is leftover from a previous version of Gun that would allow attaching per instance... but most drivers have to attach to the global instance now, and then react to enable/disable by the options passed on that.  I do know that parallel gun with different gun-file targets works (and no-targets), they are cached per-filename... if 2 gun instances use the same cache, they will share it I'm pretty sure.  The general operation of this is read-once and write-many.
I'm going to go ahead and close this... if it turns out to be an issue feel free to reopen.
